modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/wagyourtail/jsmacros"
license = "MPL-2.0"

[[mods]]
modId = "modid"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
    This is an example description! Tell everyone what your mod is about!
'''

[[mixins]]
config="modid.mixins.json"

[[dependencies.modid]]
modId="minecraft"
type = "required"
versionRange="[1.21]"
ordering="NONE"
side="BOTH"