name: Build Release
on:
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish
        run: ./gradlew publish -Pmvn.user=${{ secrets.MAVEN_USER }} -Pmvn.key=${{ secrets.MAVEN_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: Unimined Artifacts
          path: ./build/libs/

      - name: Load Gradle Properties
        uses: christian-draeger/read-properties@1.1.1
        id: gradle_properties
        with:
          path: './gradle.properties'
          properties: 'version'

      - name: Build Site
        run: ./gradlew dokkaHtml

      - name: Upload Site
        uses: nkoppel/push-files-to-another-repository@v1.1.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GH_PAGES }}
        with:
          source-files: 'build/dokka/html/'
          destination-username: 'unimined'
          destination-repository: 'unimined.github.io'
          destination-directory: 'api-docs/${{ steps.gradle_properties.outputs.version }}'
          commit-username: 'github-actions[bot]'
          commit-email: 'github-actions[bot]@users.noreply.github.com'
          commit-message: 'Update API Docs for Release ${{ steps.gradle_properties.outputs.version }}'
